#!/usr/bin/env node
// Regenerates references/*.md by extracting real values from a llama.cpp
// checkout's tools/ui webui source. Run after the webui style changes:
//
//   node .agents/skills/llamacpp-ui-style/scripts/generate.mjs [--source /path/to/llama.cpp]
//
// Every reference file below is generated, not hand-written — do not edit
// references/*.md directly, edit this script instead.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_DIR = path.resolve(SCRIPT_DIR, '..');
const REFERENCES_DIR = path.join(PACKAGE_DIR, 'references');

function parseArgs(argv) {
	const args = { source: null };
	for (let i = 0; i < argv.length; i++) {
		if (argv[i] === '--source' && argv[i + 1]) {
			args.source = argv[++i];
		}
	}
	return args;
}

function findDefaultSource() {
	// Package normally lives at <repo>/.agents/skills/llamacpp-ui-style,
	// four levels below the repo root.
	const candidate = path.resolve(PACKAGE_DIR, '..', '..', '..');
	if (fs.existsSync(path.join(candidate, 'tools/ui/src/app.css'))) return candidate;
	return null;
}

const { source: sourceArg } = parseArgs(process.argv.slice(2));
const REPO_ROOT = sourceArg ? path.resolve(sourceArg) : findDefaultSource();

if (!REPO_ROOT || !fs.existsSync(path.join(REPO_ROOT, 'tools/ui/src/app.css'))) {
	console.error(
		'Could not find tools/ui/src/app.css. Pass --source /path/to/llama.cpp (a checkout that contains tools/ui).'
	);
	process.exit(1);
}

const UI_ROOT = path.join(REPO_ROOT, 'tools/ui');
const SRC = path.join(UI_ROOT, 'src');
const read = (p) => fs.readFileSync(p, 'utf8');
const rel = (p) => path.relative(REPO_ROOT, p);

// ---------- helpers ----------

// Extracts the `{ ... }` body that follows `selector` in `text`, handling nesting.
function extractBlock(text, selector) {
	const start = text.indexOf(selector);
	if (start === -1) return null;
	const braceStart = text.indexOf('{', start);
	if (braceStart === -1) return null;
	let depth = 0;
	for (let i = braceStart; i < text.length; i++) {
		if (text[i] === '{') depth++;
		else if (text[i] === '}') {
			depth--;
			if (depth === 0) return text.slice(braceStart + 1, i);
		}
	}
	return null;
}

function parseCustomProperties(blockText) {
	const vars = [];
	const re = /--([\w-]+):\s*([^;]+);/g;
	let m;
	while ((m = re.exec(blockText))) {
		vars.push([m[1], m[2].trim()]);
	}
	return vars;
}

function walk(dir, exts, out = []) {
	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) walk(full, exts, out);
		else if (exts.some((ext) => entry.name.endsWith(ext))) out.push(full);
	}
	return out;
}

function generatedHeader(sourceFiles) {
	const list = sourceFiles.map((f) => `- \`${rel(f)}\``).join('\n');
	return `<!--
AUTO-GENERATED by scripts/generate.mjs — do not hand-edit.
Regenerate with: node scripts/generate.mjs --source /path/to/llama.cpp
Extracted on: ${new Date().toISOString().slice(0, 10)}
Source files:
${list}
-->
`;
}

// ---------- 1. colors.md ----------

function generateColors() {
	const appCssPath = path.join(SRC, 'app.css');
	const css = read(appCssPath);

	const rootBlock = extractBlock(css, ':root {') ?? extractBlock(css, ':root{');
	const darkBlock = extractBlock(css, '.dark {') ?? extractBlock(css, '.dark{');
	const themeBlock = extractBlock(css, '@theme inline {');

	const rootVars = new Map(parseCustomProperties(rootBlock ?? ''));
	const darkVars = new Map(parseCustomProperties(darkBlock ?? ''));
	const themeVars = parseCustomProperties(themeBlock ?? '');

	const allNames = Array.from(new Set([...rootVars.keys(), ...darkVars.keys()]));

	let out = generatedHeader([appCssPath]);
	out += `# Color tokens (extracted from \`${rel(appCssPath)}\`)\n\n`;
	out += `All colors are semantic CSS custom properties defined in oklch(). Reference them by\n`;
	out += `Tailwind utility name (\`bg-background\`, \`text-foreground\`, \`border-border\`, ...), never\n`;
	out += `as raw hex/rgb. Dark mode is a \`.dark\` class toggle, not a media query.\n\n`;
	out += `| token | light (\`:root\`) | dark (\`.dark\`) |\n|---|---|---|\n`;
	for (const name of allNames) {
		const light = rootVars.get(name) ?? '_(dark only)_';
		const dark = darkVars.get(name) ?? '_(same as light)_';
		out += `| \`--${name}\` | \`${light}\` | \`${dark}\` |\n`;
	}

	if (themeVars.length) {
		out += `\n## \`@theme inline\` mappings (Tailwind utility <-> CSS var)\n\n`;
		out += `| Tailwind theme var | maps to |\n|---|---|\n`;
		for (const [name, value] of themeVars) {
			out += `| \`--${name}\` | \`${value}\` |\n`;
		}
	}

	fs.writeFileSync(path.join(REFERENCES_DIR, 'colors.md'), out);
	console.log('wrote references/colors.md');
}

// ---------- 2. tokens.md (radius/font/spacing + utility frequency) ----------

function countOccurrences(files, needle) {
	let count = 0;
	let fileCount = 0;
	for (const f of files) {
		const contents = read(f);
		const matches = contents.match(new RegExp(needle, 'g'));
		if (matches) {
			count += matches.length;
			fileCount++;
		}
	}
	return { count, fileCount };
}

function generateTokens() {
	const appCssPath = path.join(SRC, 'app.css');
	const css = read(appCssPath);
	const rootBlock = extractBlock(css, ':root {') ?? '';
	const rootVars = new Map(parseCustomProperties(rootBlock));

	const svelteFiles = walk(SRC, ['.svelte']);

	const utilityProbes = [
		'backdrop-blur-sm',
		'backdrop-blur-md',
		'backdrop-blur-lg',
		'backdrop-blur-xl',
		'shadow-sm',
		'shadow-md',
		'rounded-md',
		'rounded-lg',
		'rounded-xl',
		'rounded-2xl',
		'rounded-3xl',
		'rounded-full',
		'border-border/30',
		'border-border/20'
	];

	let out = generatedHeader([appCssPath]);
	out += `# Layout tokens & utility-usage frequency\n\n`;
	out += `## Radius, fonts, layout variables (from \`:root\`)\n\n`;
	const oneLine = (v) => v.replace(/\s+/g, ' ').trim();
	out += `| token | value |\n|---|---|\n`;
	for (const name of ['radius', 'font-mono', 'layer-popover']) {
		if (rootVars.has(name)) out += `| \`--${name}\` | \`${oneLine(rootVars.get(name))}\` |\n`;
	}
	for (const [name, value] of rootVars) {
		if (name.startsWith('chat-form') || name === 'max-message-height') {
			out += `| \`--${name}\` | \`${oneLine(value)}\` |\n`;
		}
	}

	out += `\n## Utility-class frequency across \`tools/ui/src/**/*.svelte\` (${svelteFiles.length} files scanned)\n\n`;
	out += `Counted to show which conventions are actually load-bearing vs. incidental — reuse the\n`;
	out += `high-frequency ones (backdrop-blur + low-alpha border = the project's "glass panel" look;\n`;
	out += `rounded-xl/2xl dominate over sharp corners).\n\n`;
	out += `| utility | occurrences | files using it |\n|---|---|---|\n`;
	for (const probe of utilityProbes) {
		const escaped = probe.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace('/', '\\/');
		const { count, fileCount } = countOccurrences(svelteFiles, escaped);
		if (count > 0) out += `| \`${probe}\` | ${count} | ${fileCount} |\n`;
	}

	fs.writeFileSync(path.join(REFERENCES_DIR, 'tokens.md'), out);
	console.log('wrote references/tokens.md');
}

// ---------- 3. components.md ----------

function extractNamedConst(text, constName) {
	const marker = `export const ${constName}`;
	const idx = text.indexOf(marker);
	if (idx === -1) return null;
	const braceStart = text.indexOf('{', idx);
	if (braceStart === -1) return null;
	let depth = 0;
	for (let i = braceStart; i < text.length; i++) {
		if (text[i] === '{') depth++;
		else if (text[i] === '}') {
			depth--;
			if (depth === 0) return text.slice(idx, i + 2); // include trailing `})`
		}
	}
	return null;
}

// Finds every `export const <name> = tv({ ... });` block in a file, regardless of name.
function extractAllTvBlocks(text) {
	const blocks = [];
	const re = /export const (\w+) = tv\(\{/g;
	let m;
	while ((m = re.exec(text))) {
		const braceStart = text.indexOf('{', re.lastIndex - 1);
		let depth = 0;
		for (let i = braceStart; i < text.length; i++) {
			if (text[i] === '{') depth++;
			else if (text[i] === '}') {
				depth--;
				if (depth === 0) {
					blocks.push({ name: m[1], code: text.slice(m.index, i + 2) });
					break;
				}
			}
		}
	}
	return blocks;
}

function extractVariantNames(tvBlock) {
	const variantsBlock = extractBlock(tvBlock, 'variants: {');
	if (!variantsBlock) return null;
	const keys = [];
	const re = /^\s*(\w[\w-]*):\s*\{/gm;
	let m;
	while ((m = re.exec(variantsBlock))) keys.push(m[1]);
	return keys;
}

// Generates one references/components/<name>.md per ui/ primitive folder: full
// tv() variant blocks where present, otherwise the whole (small) source verbatim.
function generateComponentDetail(uiDir, componentName) {
	const compDir = path.join(uiDir, componentName);
	const files = fs
		.readdirSync(compDir, { withFileTypes: true })
		.filter((e) => e.isFile() && (e.name.endsWith('.svelte') || e.name.endsWith('.ts')))
		.map((e) => path.join(compDir, e.name))
		.sort();

	let out = generatedHeader(files);
	out += `# \`${componentName}\`\n\n`;
	let variantSummary = [];

	for (const f of files) {
		const src = read(f);
		const tvBlocks = extractAllTvBlocks(src);
		const fence = f.endsWith('.ts') ? 'ts' : 'svelte';
		out += `## \`${rel(f)}\`\n\n`;
		if (tvBlocks.length) {
			for (const block of tvBlocks) {
				const variantNames = extractVariantNames(block.code);
				if (variantNames) variantSummary.push(...variantNames.map((v) => `${block.name}:${v}`));
				out += `\`\`\`ts\n${block.code}\n\`\`\`\n\n`;
			}
		} else {
			out += `\`\`\`${fence}\n${src.trim()}\n\`\`\`\n\n`;
		}
	}

	fs.mkdirSync(path.join(REFERENCES_DIR, 'components'), { recursive: true });
	fs.writeFileSync(path.join(REFERENCES_DIR, 'components', `${componentName}.md`), out);
	return variantSummary;
}

function generateComponents() {
	const uiDir = path.join(SRC, 'lib/components/ui');
	const utilsPath = path.join(uiDir, 'utils.ts');
	const cssClassesPath = path.join(SRC, 'lib/constants/css-classes.ts');

	const uiComponents = fs
		.readdirSync(uiDir, { withFileTypes: true })
		.filter((e) => e.isDirectory())
		.map((e) => e.name)
		.sort();

	const perComponentVariants = new Map();
	for (const name of uiComponents) {
		perComponentVariants.set(name, generateComponentDetail(uiDir, name));
	}

	let out = generatedHeader([utilsPath, cssClassesPath, path.join(uiDir, '<each component>/*')]);
	out += `# Component inventory (index)\n\n`;
	out += `Every shadcn-svelte primitive under \`${rel(uiDir)}/\` gets its own fully-extracted\n`;
	out += `reference at \`references/components/<name>.md\` (verbatim \`tv()\` variant blocks where a\n`;
	out += `component defines variants, full source otherwise). Reuse one of these before building a\n`;
	out += `new primitive from scratch.\n\n`;
	out += `| component | variants defined | detail file |\n|---|---|---|\n`;
	for (const name of uiComponents) {
		const variants = perComponentVariants.get(name);
		const summary = variants && variants.length ? variants.join(', ') : '_(no tv() variants)_';
		out += `| \`${name}\` | ${summary} | \`references/components/${name}.md\` |\n`;
	}

	const utilsSrc = read(utilsPath);
	out += `\n## Class-merge utility (\`${rel(utilsPath)}\`)\n\n\`\`\`ts\n${utilsSrc.trim()}\n\`\`\`\n\n`;
	out += `Always merge classes through \`cn()\` (clsx + tailwind-merge) instead of string concatenation,\n`;
	out += `so consumer overrides (\`class="..."\`) win over base variant classes.\n\n`;

	const cssClassesSrc = read(cssClassesPath);
	out += `## Shared class-string constants (\`${rel(cssClassesPath)}\`)\n\n\`\`\`ts\n${cssClassesSrc.trim()}\n\`\`\`\n`;

	fs.writeFileSync(path.join(REFERENCES_DIR, 'components.md'), out);
	console.log(
		`wrote references/components.md + references/components/*.md (${uiComponents.length} components)`
	);
}

// ---------- 4. icons.md ----------

function generateIcons() {
	const allFiles = walk(SRC, ['.svelte', '.ts']);
	const usage = new Map(); // icon name -> Set of files

	const importRe = /import\s*\{([^}]+)\}\s*from\s*['"]@lucide\/svelte['"];?/g;
	for (const f of allFiles) {
		const content = read(f);
		let m;
		importRe.lastIndex = 0;
		while ((m = importRe.exec(content))) {
			const names = m[1]
				.split(',')
				.map((n) => n.trim())
				.filter(Boolean)
				.map((n) => n.split(' as ')[0].trim());
			for (const name of names) {
				if (!usage.has(name)) usage.set(name, new Set());
				usage.get(name).add(rel(f));
			}
		}
	}

	const sorted = Array.from(usage.entries()).sort((a, b) => a[0].localeCompare(b[0]));

	let out = generatedHeader([path.join(SRC, '**/*.svelte'), path.join(SRC, '**/*.ts')]);
	out += `# Icon usage inventory\n\n`;
	out += `Icon library: \`@lucide/svelte\` only — ${sorted.length} distinct icons in use across\n`;
	out += `${allFiles.length} scanned files. Do not introduce another icon set; pick the closest existing\n`;
	out += `lucide icon, or add a new lucide import following the same pattern.\n\n`;
	out += `| icon | used in (# files) |\n|---|---|\n`;
	for (const [name, files] of sorted) {
		out += `| \`${name}\` | ${files.size} |\n`;
	}

	fs.writeFileSync(path.join(REFERENCES_DIR, 'icons.md'), out);
	console.log('wrote references/icons.md');
}

// ---------- 5. sidebar.md ----------

function generateSidebar() {
	const sidebarPath = path.join(
		SRC,
		'lib/components/app/navigation/SidebarNavigation/SidebarNavigation.svelte'
	);
	if (!fs.existsSync(sidebarPath)) {
		console.warn('SidebarNavigation.svelte not found, skipping sidebar.md');
		return;
	}
	const src = read(sidebarPath);

	const asideMatch = src.match(/<aside[\s\S]*?<\/aside>/);
	const styleMatch = src.match(/<style>[\s\S]*?<\/style>/);

	let out = generatedHeader([sidebarPath]);
	out += `# Sidebar navigation shell (extracted from \`${rel(sidebarPath)}\`)\n\n`;
	out += `Collapsed-to-expanded icon-strip sidebar pattern used for the primary nav. Key behavior:\n`;
	out += `collapsed = icon rail (\`md:w-12\`), expanded = \`md:w-72\` panel with\n`;
	out += `\`md:bg-muted/60 md:backdrop-blur-xl\`, animated via \`transition-[width,padding] duration-200\n`;
	out += `ease-out\`. Mobile uses a fixed full-width overlay instead of a side rail.\n\n`;
	out += `## Markup (root \`<aside>\` element, verbatim)\n\n\`\`\`svelte\n${(asideMatch?.[0] ?? '(not found)').trim()}\n\`\`\`\n\n`;
	if (styleMatch) {
		out += `## Scoped styles\n\n\`\`\`css\n${styleMatch[0].replace(/<\/?style>/g, '').trim()}\n\`\`\`\n`;
	}

	fs.writeFileSync(path.join(REFERENCES_DIR, 'sidebar.md'), out);
	console.log('wrote references/sidebar.md');
}

// ---------- 6. typography.md ----------

function generateTypography() {
	const mdCssPath = path.join(
		SRC,
		'lib/components/app/content/MarkdownContent/markdown-content.css'
	);
	if (!fs.existsSync(mdCssPath)) {
		console.warn('markdown-content.css not found, skipping typography.md');
		return;
	}
	const css = read(mdCssPath);

	const headingSizes = [];
	for (const tag of ['h1', 'h2', 'h3', 'h4', 'h5', 'h6']) {
		const block = extractBlock(css, `:global(${tag}) {`);
		if (!block) continue;
		const size = block.match(/font-size:\s*([^;]+);/)?.[1]?.trim();
		const weight = block.match(/font-weight:\s*([^;]+);/)?.[1]?.trim();
		const lineHeight = block.match(/line-height:\s*([^;]+);/)?.[1]?.trim();
		const margin = block.match(/margin:\s*([^;]+);/)?.[1]?.trim();
		headingSizes.push({ tag, size, weight, lineHeight, margin });
	}

	let out = generatedHeader([mdCssPath, path.join(SRC, 'app.css')]);
	out += `# Typography\n\n`;
	out += `## Fonts\n\n`;
	out += `- Base UI font: Tailwind's default sans stack (no custom webfont is loaded — no \`<link>\`\n`;
	out += `  to Google Fonts etc. in \`src/app.html\`).\n`;
	out += `- Monospace (code/kbd/pre/inline-code): \`--font-mono\` in \`app.css\` —\n`;
	out += `  \`ui-monospace, SFMono-Regular, 'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas,\n`;
	out += `  'Liberation Mono', Menlo, monospace\`.\n\n`;
	out += `## Markdown content heading scale (\`${rel(mdCssPath)}\`)\n\n`;
	out += `| tag | font-size | font-weight | line-height | margin |\n|---|---|---|---|---|\n`;
	for (const h of headingSizes) {
		out += `| \`${h.tag}\` | ${h.size ?? '-'} | ${h.weight ?? '-'} | ${h.lineHeight ?? '-'} | ${h.margin ?? '-'} |\n`;
	}
	out += `\nBody paragraph: \`line-height: 1.75\`, \`margin-block: 1rem\`. Responsive downshift at\n`;
	out += `\`max-width: 640px\` (h1→1.5rem, h2→1.25rem, h3→1.125rem).\n`;

	fs.writeFileSync(path.join(REFERENCES_DIR, 'typography.md'), out);
	console.log('wrote references/typography.md');
}

// ---------- run ----------

fs.mkdirSync(REFERENCES_DIR, { recursive: true });
generateColors();
generateTokens();
generateComponents();
generateIcons();
generateSidebar();
generateTypography();
console.log(`\nDone. Source: ${REPO_ROOT}`);
